name:                puddle
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/puddle#readme
license:             BSD3
author:              June Woodward
maintainer:          jlwoodwa@caltech.edu
copyright:           2020 June Woodward
category:            Compilers/Interpreters
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - parsec
  - containers
  - text
  - mtl
  - lens
  - either
  - monad-loops
  - yjtools


executables:
  puddle:
    source-dirs:      src
    main:             Main.hs

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wunused-imports

default-extensions:
  # Trivial
  [ EmptyCase
  , FlexibleContexts
  , FlexibleInstances
  , InstanceSigs
  , MultiParamTypeClasses
  # Convenience
  , LambdaCase
  , MultiWayIf
  , NamedFieldPuns
  , TupleSections
  # `deriving` extensions
  , DeriveFoldable
  , DeriveFunctor
  , DeriveGeneric
  , DeriveLift
  , DeriveTraversable
  , DerivingStrategies
  , GeneralizedNewtypeDeriving
  # Syntax adjustments
  , BangPatterns
  , KindSignatures
  , TypeOperators
  # String overloading
  , OverloadedStrings
  # Type annotation
  , ScopedTypeVariables
  , TypeApplications
  # Type extensions
  , ConstraintKinds
  , RankNTypes
  # More syntax adjustments
  , ApplicativeDo
  , DefaultSignatures
  , PatternSynonyms
  ]
