name:                puddle
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/puddle#readme
license:             BSD3
author:              June Woodward
maintainer:          jlwoodwa@caltech.edu
copyright:           2020 June Woodward
category:            Compilers/Interpreters
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - parsec
  - either
  - extra
  - unordered-containers


executables:
  puddle:
    source-dirs:      src
    main:             Main.hs
